{
 "title": "lolMiner",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Session Performance [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "MHs" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(lolminer_session_performance_total_mhps[$__rate_interval])",
     "legendFormat": "Session"
    }
   ]
  },
  {
   "title": "Session Power [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(lolminer_session_power_total_watts[$__rate_interval])",
     "legendFormat": "Session"
    }
   ]
  },
  {
   "title": "Session Percentage Accepted Shares (hourly) [15m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * rate(lolminer_session_accepted_shares_total[$__rate_interval]) / rate(lolminer_session_submitted_shares_total[$__rate_interval])",
     "legendFormat": "Session"
    }
   ]
  },
  {
   "title": "GPU Temperature [1m]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(lolminer_gpu_temperature_celsius[$__rate_interval]) * on(gpu_index) group_left(name) lolminer_gpu_info",
     "legendFormat": "GPU #{{gpu_index}} ({{name}})"
    }
   ]
  },
  {
   "title": "Session",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Session Performance [1m]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "MHs" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(lolminer_session_performance_total_mhps[$__rate_interval])",
       "legendFormat": "Session"
      }
     ]
    },
    {
     "title": "Session Power [1m]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "watt" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(lolminer_session_power_total_watts[$__rate_interval])",
       "legendFormat": "Session"
      }
     ]
    },
    {
     "title": "Session Uptime [1m]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(lolminer_session_uptime_seconds[$__rate_interval])",
       "legendFormat": "Session"
      }
     ]
    },
    {
     "title": "Active GPUs [1m]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(lolminer_session_active_gpus[$__rate_interval])",
       "legendFormat": "Session"
      }
     ]
    },
    {
     "title": "Session Accepted Shares (hourly) [15m]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "3600 * rate(lolminer_session_accepted_shares_total[$__rate_interval])",
       "legendFormat": "Session"
      }
     ]
    },
    {
     "title": "Session Percentage Accepted Shares (hourly) [15m]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * rate(lolminer_session_accepted_shares_total[$__rate_interval]) / rate(lolminer_session_submitted_shares_total[$__rate_interval])",
       "legendFormat": "Session"
      }
     ]
    },
    {
     "title": "Session Submitted Shares (hourly) [15m]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "3600 * rate(lolminer_session_submitted_shares_total[$__rate_interval])",
       "legendFormat": "Session"
      }
     ]
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Performance [1m]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "MHs" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(lolminer_gpu_performance_mhps[$__rate_interval]) * on(gpu_index) group_left(name) lolminer_gpu_info",
       "legendFormat": "GPU #{{gpu_index}} ({{name}})"
      }
     ]
    },
    {
     "title": "GPU Power [1m]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "watt" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(lolminer_gpu_power_watts[$__rate_interval]) * on(gpu_index) group_left(name) lolminer_gpu_info",
       "legendFormat": "GPU #{{gpu_index}} ({{name}})"
      }
     ]
    },
    {
     "title": "GPU Temperature [1m]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(lolminer_gpu_temperature_celsius[$__rate_interval]) * on(gpu_index) group_left(name) lolminer_gpu_info",
       "legendFormat": "GPU #{{gpu_index}} ({{name}})"
      }
     ]
    },
    {
     "title": "GPU Fan Speed [1m]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * avg_over_time(lolminer_gpu_fan_speed[$__rate_interval]) * on(gpu_index) group_left(name) lolminer_gpu_info",
       "legendFormat": "GPU #{{gpu_index}} ({{name}})"
      }
     ]
    },
    {
     "title": "GPU Accepted Shares (hourly) [15m]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "3600 * rate(lolminer_gpu_session_accepted_shares_total[$__rate_interval]) * on(gpu_index) group_left(name) lolminer_gpu_info",
       "legendFormat": "GPU #{{gpu_index}} ({{name}})"
      }
     ]
    },
    {
     "title": "GPU Percentage Accepted Shares (hourly) [15m]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * rate(lolminer_gpu_session_accepted_shares_total[$__rate_interval]) / rate(lolminer_gpu_session_submitted_shares_total[$__rate_interval]) * on(gpu_index) group_left(name) lolminer_gpu_info",
       "legendFormat": "GPU #{{gpu_index}} ({{name}})"
      }
     ]
    },
    {
     "title": "GPU Submitted Shares (hourly) [15m]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "3600 * rate(lolminer_gpu_session_submitted_shares_total[$__rate_interval]) * on(gpu_index) group_left(name) lolminer_gpu_info",
       "legendFormat": "GPU #{{gpu_index}} ({{name}})"
      }
     ]
    },
    {
     "title": "GPU Hardware Errors [1m]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "3600 * rate(lolminer_gpu_session_hardware_errors_total[$__rate_interval]) * on(gpu_index) group_left(name) lolminer_gpu_info",
       "legendFormat": "GPU #{{gpu_index}} ({{name}})"
      }
     ]
    }
   ]
  }
 ]
}